services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
    volumes:
      - agreementsdb:/var/lib/postgresql
    ports:
      - 5432:5432

volumes:
  agreementsdb:
    external: true
    name: relationshipagreements_agreementsdb